import {
    HiOutlineColorSwatch,
    HiOutlineDesktopComputer,
    HiOutlineTemplate,
    HiOutlineViewGridAdd,
    HiOutlineHome,
    HiAdjustments,
    HiOutlineFilter,
    HiOutlineSearch,
    HiCurrencyDollar,
    HiOutlineCreditCard,
    HiOutlineCalendar,
    HiDocumentAdd,
    HiOutlineCash,
    HiOutlineTrash,
    HiOutlinePencil,
    HiOutlineClipboardList,
    HiOutlineCog,
    HiOutlineCubeTransparent,
    HiOutlineFingerPrint,
    HiOutlineCollection,
    HiOutlineArchive,
    HiOutlineUserGroup,
    HiOutlineArrowDown,
    HiOutlineArrowUp,
} from 'react-icons/hi'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    add: <HiDocumentAdd />,
    home: <HiOutlineHome />,
    singleMenu: <HiOutlineViewGridAdd />,
    matList: <HiOutlineClipboardList />,
    swatch: <HiOutlineColorSwatch />,
    income: <HiCurrencyDollar />,
    accounts: <HiCurrencyDollar />,
    edit: <HiOutlinePencil />,
    delete: <HiOutlineTrash />,
    expenses: <HiOutlineCreditCard />,
    budget: <HiOutlineCash />,
    calendar: <HiOutlineCalendar />,
    collapseMenu: <HiOutlineTemplate />,
    groupSingleMenu: <HiOutlineDesktopComputer />,
    groupCollapseMenu: <HiOutlineColorSwatch />,
    settings: <HiAdjustments />,
    filter: <HiOutlineFilter />,
    search: <HiOutlineSearch />,
    cog: <HiOutlineCog />,
    cubeTrans: <HiOutlineCubeTransparent />,
    finger: <HiOutlineFingerPrint />,
    collection: <HiOutlineCollection />,
    archive: <HiOutlineArchive />,
    group: <HiOutlineUserGroup />,
    up: <HiOutlineArrowUp />,
    down: <HiOutlineArrowDown />,
}

export default navigationIcon
