import {
    HiOutlineColorSwatch,
    HiOutlineDesktopComputer,
    HiOutlineTemplate,
    HiOutlineViewGridAdd,
    HiAdjustments,
    HiOutlineFilter,
    HiOutlineSearch,
    HiCurrencyDollar,
    HiOutlineCreditCard,
    HiOutlineCalendar,
    HiDocumentAdd,
    HiOutlineTrash,
    HiOutlinePencil,
    HiOutlineFingerPrint,
    HiOutlineCollection,
    HiOutlineArrowDown,
    HiOutlineArrowUp,
} from 'react-icons/hi'
import {
    HiOutlineClipboardDocumentList,
    HiOutlineCog8Tooth,
    HiOutlineUserGroup,
    HiOutlineHome,
    HiOutlineSwatch,
    HiOutlineCubeTransparent,
    HiOutlineArchiveBox,
    HiOutlineBanknotes,
} from 'react-icons/hi2'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    add: <HiDocumentAdd />,
    home: <HiOutlineHome />,
    singleMenu: <HiOutlineViewGridAdd />,
    matList: <HiOutlineClipboardDocumentList />,
    swatch: <HiOutlineSwatch />,
    income: <HiCurrencyDollar />,
    accounts: <HiCurrencyDollar />,
    edit: <HiOutlinePencil />,
    delete: <HiOutlineTrash />,
    expenses: <HiOutlineCreditCard />,
    budget: <HiOutlineBanknotes />,
    calendar: <HiOutlineCalendar />,
    collapseMenu: <HiOutlineTemplate />,
    groupSingleMenu: <HiOutlineDesktopComputer />,
    groupCollapseMenu: <HiOutlineColorSwatch />,
    settings: <HiAdjustments />,
    filter: <HiOutlineFilter />,
    search: <HiOutlineSearch />,
    cog: <HiOutlineCog8Tooth />,
    cubeTrans: <HiOutlineCubeTransparent />,
    finger: <HiOutlineFingerPrint />,
    collection: <HiOutlineCollection />,
    archive: <HiOutlineArchiveBox />,
    group: <HiOutlineUserGroup />,
    up: <HiOutlineArrowUp />,
    down: <HiOutlineArrowDown />,
}

export default navigationIcon
